server {
    listen 80;
    server_name _;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://C4lendar-BE:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api-docs {
        proxy_pass http://C4lendar-BE:4000/api-docs;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 401 /index.html;
    error_page 404 /404.html;

    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
